### ISSUE TITLE
Create Email Notification Workflow for CI/CD Pipeline

### ISSUE THREAD

**Issue by JANHAVIKULKARNI12** [JANHAVIKULKARNI12/HOMELESSNESS_PREVENTION#38]
Description: The current CI/CD pipeline lacks a comprehensive email notification system to notify users of the success or failure of the workflow. We need to create a workflow that sends email notifications after the completion of each pipeline run. The workflow should send:
A success email if the pipeline completes successfully.
A failure email if the pipeline encounters any issues.
The email notifications should include relevant information, such as the status of the pipeline and the potential cause of failure, in case of errors.
Steps to implement:
Add Python code within the workflow to send email notifications using SMTP (e.g., Gmail).
Configure the email content, including the subject and body, based on the pipeline's result (success or failure).
Test the email notifications by running the CI/CD pipeline with different outcomes (successful run and failed run).
Ensure that the emails are sent only if the relevant conditions (success or failure) are met.
Expected outcome:
The workflow will automatically send a notification email after the pipeline run.
Success emails will indicate that the pipeline completed successfully.
Failure emails will provide error details and encourage users to check logs for further information.

**Comment by vaniwalvekar** [comment]
Issue resolved through Pull Request #35.

Added email notifications for pipeline success and failure.
Tested for reliability with both scenarios.
Closing this now.
