### ISSUE TITLE
implement the UI for the complete web application.

### ISSUE THREAD

**Issue by iamvenkat1003** [JANHAVIKULKARNI12/HOMELESSNESS_PREVENTION#48]
add a proper background and also make sure the design of buttons and the borders are looking good.

**Comment by vaniwalvekar** [comment]
The issue has been resolved with the implementation of UI enhancements as part of PR #44. The background has been properly designed, and the button styles, including borders and hover effects, have been improved for a more polished and user-friendly interface. The changes have been successfully pushed and merged, closing the issue.
